# Generated by Django 5.2.3 on 2025-06-22 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_task_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
    ]
